name: Update README

on:
  push:
    paths:
      - '**/**'        # Run when any file is pushed
  schedule:
    - cron: '0 3 * * *' # Run daily at 3 AM UTC

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Run README generator
      run: python scripts/generate_readme.py

    - name: Commit and push README
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add README.md
        git commit -m "🔄 Auto-update README from GitHub Action" || echo "No changes"
        git push
